version: "3"
services:
  aoc-js:
    build: .
    container_name: aoc-js
    image: quyo/aoc.js:dev
    restart: "no"
    ports:
      - 3000:3000
    networks:
      - external

networks:
  external:
    name: aoc-js_external
