version: "3"
services:

  aoc:
    build: .
    container_name: aoc
    image: quyo/aoc.js:latest
    restart: "no"
    ports:
      - 3000:3000
    networks:
      - external

networks:
  external:
    name: aoc_external
