# fly.toml file generated for quyo-aoc on 2022-12-17T19:27:56+01:00

app = "quyo-aoc"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  AOCJS_ENV_LABEL = "FLY"

[[services]]
  internal_port = 3000
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "requests"

  [[services.http_checks]]
    grace_period = "5s"
    interval = 10000
    method = "get"
    path = "/"
    protocol = "http"
    restart_limit = 0
    timeout = 2000
    tls_skip_verify = false
    [services.http_checks.headers]

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
